---
# Flagd UI - Feature Flag Configuration Interface
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-demo-flagd-ui
  labels:
    opentelemetry.io/name: opentelemetry-demo-flagd-ui
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/component: flagd-ui
    app.kubernetes.io/name: opentelemetry-demo-flagd-ui
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-flagd-ui
  template:
    metadata:
      labels:
        opentelemetry.io/name: opentelemetry-demo-flagd-ui
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/component: flagd-ui
        app.kubernetes.io/name: opentelemetry-demo-flagd-ui
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: flagd-ui
          image: ghcr.io/open-telemetry/demo:1.12.0-flagd-ui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: 'opentelemetry-demo-otelcol'
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: FLAGD_UI_PORT
              value: "4000"
            - name: SECRET_KEY_BASE
              value: "yYrECL4qbNwleYInGJYvVnSkwJuSQJ4ijPTx5tirGUXrbznFIBFVJdPl5t6O9ASw"
            - name: PHX_HOST
              value: "localhost"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_COLLECTOR_NAME):4318
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
          resources:
            limits:
              memory: 200Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 100m
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 10
          volumeMounts:
            - name: flagd-config
              mountPath: /app/data
      volumes:
        - name: flagd-config
          configMap:
            name: opentelemetry-demo-flagd-config
