---
# Flagd UI Service
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-flagd-ui
  labels:
    opentelemetry.io/name: opentelemetry-demo-flagd-ui
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/component: flagd-ui
    app.kubernetes.io/name: opentelemetry-demo-flagd-ui
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    opentelemetry.io/name: opentelemetry-demo-flagd-ui
